site_name: IoT Book
site_description: 介绍物联网基础概念
site_author: WiSys Lob

theme:
    name: material
    palette:
      primary: 'Blue Grey'
      accent: 'Deep Orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - matlab
    language: 'zh'
    logo: 'images/cbd47-7mlgx-001.ico'

extra:
  social:
    - type: github
      link: https://github.com/iot-book
  search:
    language: 'zh'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - 一. 前言: IoTBook/1. 前言/物联网导论.md
  - 二. 物联网简介: IoTBook/2. 物联网简介/物联网简介.md


  - 三. 开发环境:
      - 3.1 Android 环境: IoTBook/平台搭建/android开发基础.md
      - 3.2 MATLAB 环境: IoTBook/平台搭建/matlab基础.md



  - 四. 物联网网络协议: 
      - 4.1 物联网连接技术: IoTBook/3. 物联网通信协议/物联网连接技术.md
      - 4.2 蓝牙连接实验: IoTBook/3. 物联网通信协议/蓝牙实验.md
      - 4.3 LoRa编码和通信实验: IoTBook/3. 物联网通信协议/LoRa编码和通信实验.md



  - 五. 物联网通信基础: 
      - 5.1 物联网基础概念: IoTBook/4. 物联网通信基础/4.1 物联网基础概念.md
        # - 5.1.1 量化、采样及采样定律: IoTBook/4. 物联网通信基础/4.1 物联网基础概念.md
        # - 5.1.2 滤波: IoTBook/4. 物联网通信基础/4.1.3 滤波.md
        # - 5.1.3 傅立叶分析: IoTBook/4. 物联网通信基础/4.1.2 傅里叶分析.md
      - 5.2 调制解调方法: IoTBook/4. 物联网通信基础/4.2 调制解调方法及其声音实现.md
        # - 5.2.1 脉冲、幅度、时间、频率编码: IoTBook/4. 物联网通信基础/4.2 调制解调方法及其声音实现.md
        # - 5.2.2 相位编码、OFDM与载波调制: IoTBook/4. 物联网通信基础/4.2 调制解调方法及其声音实现-2.md



  - 六. 物联网网络构建技术:
      - 6.1 低功耗物联网:
        - 6.1.1 概述: IoTBook/8. 物联网网络构建/8.1 低功耗物联网概述.md
        - 6.1.2 低占空比网络: IoTBook/8. 物联网网络构建/8.1.1 低占空比网络.md
        - 6.1.3 低功耗广域网: IoTBook/8. 物联网网络构建/8.1.2 低功耗广域网.md
      - 6.2 多跳自组织网: IoTBook/8. 物联网网络构建/8.5 物联网多跳自组网网络协议.md
      - 6.3 网络冲突处理:
        - 6.3.1 概述: IoTBook/8. 物联网网络构建/8.2 网络冲突处理.md
        - 6.3.2 zigzag的声音实现: IoTBook/8. 物联网网络构建/8.2.2 zigzag实验.md
        - 6.3.3 链路模型及网络容量: IoTBook/8. 物联网网络构建/8.2.1 链路模型及网络容量.md
      - 6.4 跨协议识别与通信:
        - 6.4.1 跨协议识别: IoTBook/8. 物联网网络构建/8.3 跨协议识别.md
        - 6.4.2 跨协议通信: IoTBook/8. 物联网网络构建/8.4 跨协议通信.md





  - 七. 物联网定位与追踪:
      - 7.1 无线测距:
        - 7.1.1 ToF测距: IoTBook/5.物联网感知/飞行时间.md
        - 7.1.2 多普勒效应测距: IoTBook/5.物联网感知/多普勒效应.md
        - 7.1.3 相位测距: IoTBook/5.物联网感知/相位偏移.md
        - 7.1.4 FMCW测距: IoTBook/404.md
      - 7.2 定位技术:
        - 7.2.1 基于距离测量的定位: IoTBook/6. 定位与追踪应用/7.1基于距离测量的定位.md
        - 7.2.2 基于信号分布特征的定位: IoTBook/6. 定位与追踪应用/7.2基于信号分布特征的定位.md
        - 7.2.3 基于相位的定位: IoTBook/6. 定位与追踪应用/LLAP/LLAP实现.md
      - 7.3 追踪技术:
        - 7.3.1 基于距离变化量的位置追踪: IoTBook/6. 定位与追踪应用/7.3基于距离变化量的位置追踪.md
        



  - 八. 物联网感知技术:
      - 8.1 传感器感知:
          - 8.1.1 传感器: IoTBook/5.物联网感知/传感器.md
          - 8.1.2 传感器实验: IoTBook/5.物联网感知/实验-传感器.md
      - 8.2 行为识别:
        - 8.2.1 Wi-Fi 动作识别: IoTBook/404.md
        - 8.2.2 智能手表连接教程: IoTBook/7.感知识别/智能手表手势识别/智能手表连接教程/智能手表连接教程.md
        - 8.2.2 智能手表数据采集: IoTBook/7.感知识别/智能手表手势识别/智能手表数据采集/智能手表数据采集.md
        - 8.2.2 数据处理与展示: IoTBook/7.感知识别/智能手表手势识别/数据处理与展示/智能手表数据处理与展示.md
      - 8.3 身份认证:
        - 8.3.1 频率选择: IoTBook/404.md
        - 8.3.2 声纹识别: IoTBook/404.md

  - 九. 物联网综合应用平台:
      - 9.1 阿里云平台: IoTBook/10. 物联网应用平台/阿里云平台/阿里云物联网平台介绍.md
      - 9.2 LoRa测试床: IoTBook/10. 物联网应用平台/LoRa测试床/LoRa测试床.md
      - 9.3 物联网开发: IoTBook/10. 物联网应用平台/物联网开发/物联网开发.md
